Montagem do Google Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import matplotlib.pyplot as plt

In [4]:
data = pd.read_csv("/content/drive/MyDrive/Ciencia de Dados/Aprendizado de maquina/loan.csv")

In [5]:
data.head(15)

     Loan_ID  Gender Married  ... Loan_Amount_Term Credit_History Property_Area
0   LP001015    Male     Yes  ...            360.0            1.0         Urban
1   LP001022    Male     Yes  ...            360.0            1.0         Urban
2   LP001031    Male     Yes  ...            360.0            1.0         Urban
3   LP001035    Male     Yes  ...            360.0            NaN         Urban
4   LP001051    Male      No  ...            360.0            1.0         Urban
5   LP001054    Male     Yes  ...            360.0            1.0         Urban
6   LP001055  Female      No  ...            360.0            1.0     Semiurban
7   LP001056    Male     Yes  ...            360.0            0.0         Rural
8   LP001059    Male     Yes  ...            240.0            1.0         Urban
9   LP001067    Male      No  ...            360.0            1.0     Semiurban
10  LP001078    Male      No  ...            360.0            1.0         Urban
11  LP001082    Male     Yes  ...            360.0            1.0     Semiurban
12  LP001083    Male      No  ...            180.0            NaN         Urban
13  LP001094    Male     Yes  ...            360.0            0.0     Semiurban
14  LP001096  Female      No  ...            360.0            1.0     Semiurban

[15 rows x 12 columns]

In [6]:
data.describe()

       ApplicantIncome  CoapplicantIncome  ...  Loan_Amount_Term  Credit_History
count       367.000000         367.000000  ...        361.000000      338.000000
mean       4805.599455        1569.577657  ...        342.537396        0.825444
std        4910.685399        2334.232099  ...         65.156643        0.380150
min           0.000000           0.000000  ...          6.000000        0.000000
25%        2864.000000           0.000000  ...        360.000000        1.000000
50%        3786.000000        1025.000000  ...        360.000000        1.000000
75%        5060.000000        2430.500000  ...        360.000000        1.000000
max       72529.000000       24000.000000  ...        480.000000        1.000000

[8 rows x 5 columns]

Verificar se o dataset tem problema de ruídos ou dados faltantes. Caso um dos problemas seja identificado, aplicar um método para tratar o problema.

In [11]:
data.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [12]:
df = data.dropna(axis=0, how='any', thresh=None, subset=['Gender', 'Dependents','Self_Employed','LoanAmount','Loan_Amount_Term','Credit_History'], inplace=True)

In [14]:
data.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

Gerar um “sample” do dataset  que mantenha as características originais dos dados. Escolha um método e utilize a função resample do sklearn.utils.

In [29]:
data.count()

Loan_ID              289
Gender               289
Married              289
Dependents           289
Education            289
Self_Employed        289
ApplicantIncome      289
CoapplicantIncome    289
LoanAmount           289
Loan_Amount_Term     289
Credit_History       289
Property_Area        289
dtype: int64

In [28]:
subset = data.sample(n=100)
subset.describe()

       ApplicantIncome  CoapplicantIncome  ...  Loan_Amount_Term  Credit_History
count       100.000000         100.000000  ...        100.000000      100.000000
mean       4361.890000        1556.780000  ...        348.380000        0.880000
std        3238.992248        1723.390296  ...         55.464026        0.326599
min        1300.000000           0.000000  ...         84.000000        0.000000
25%        2609.750000           0.000000  ...        360.000000        1.000000
50%        3643.500000        1406.000000  ...        360.000000        1.000000
75%        4414.500000        2630.750000  ...        360.000000        1.000000
max       24797.000000        7916.000000  ...        480.000000        1.000000

[8 rows x 5 columns]

In [22]:
from sklearn.utils import resample

In [44]:
resample(data, n_samples=10, random_state=0)

      Loan_ID  Gender Married  ... Loan_Amount_Term Credit_History Property_Area
215  LP002184    Male     Yes  ...            300.0            1.0         Urban
60   LP001332    Male     Yes  ...            360.0            1.0     Semiurban
147  LP001817    Male      No  ...            360.0            0.0         Rural
237  LP002325    Male     Yes  ...            360.0            1.0         Rural
321  LP002786  Female     Yes  ...            360.0            1.0         Urban
240  LP002333    Male      No  ...            360.0            1.0         Urban
14   LP001096  Female      No  ...            360.0            1.0     Semiurban
263  LP002433    Male     Yes  ...            360.0            1.0         Rural
352  LP002907    Male     Yes  ...            360.0            1.0         Urban
310  LP002746    Male      No  ...            360.0            1.0         Urban

[10 rows x 12 columns]

Escolher um atributo categóricos e utilizar a função OneHotEncoder  (Links para um site externo.) para transformar em codificação inteira-binária os valores nominais .

In [32]:
 from sklearn.preprocessing import OneHotEncoder
 from sklearn import preprocessing

In [31]:
data.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [34]:
data.shape

(289, 12)

In [36]:
le = preprocessing.LabelEncoder()
df_data = data.apply(le.fit_transform)
df_data.head()

   Loan_ID  Gender  Married  ...  Loan_Amount_Term  Credit_History  Property_Area
0        0       1        1  ...                 9               1              2
1        1       1        1  ...                 9               1              2
2        2       1        1  ...                 9               1              2
4        3       1        0  ...                 9               1              2
5        4       1        1  ...                 9               1              2

[5 rows x 12 columns]

In [38]:
enc = OneHotEncoder()
enc.fit(df_data)
onehotlabels = enc.transform(df_data).toarray()
onehotlabels.shape

(289, 854)

Aplicar pelo menos uma técnica de normalização no dataset.

In [40]:
scaler_min_max = preprocessing.MinMaxScaler()
data_scaled = scaler_min_max.fit_transform(df_data)

In [41]:
print(data_scaled.min(axis=0))
print(data_scaled.max(axis=0))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

In [42]:
data_scaled.shape

(289, 12)